# Application
spring.application.name=irctc-backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/irctc_db
spring.datasource.username=irctc_user
spring.datasource.password=irctc_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Server
server.port=8080
# jwt
# JWT
jwt.secret=irctc-super-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000